name: AI Updater Workflow (for testing)

on:
  push:
    branches:
      - workflow/update-proto
  workflow_dispatch:

jobs:
  call-ai-updater:
    uses: gabegottlob/viam-ai-updater/.github/workflows/ai-updater-test.yml@main
    with:
        target_branch: workflow/update-proto
        sdk: cpp
    secrets:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
